# Generated by Django 3.1.6 on 2021-02-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210208_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bestSellers',
            field=models.BooleanField(default=False),
        ),
    ]
